# Generated by Django 4.2.13 on 2024-07-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_web_stats', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$eyeJMRs29TUVuUxQMjvqld$l+MY1pMQ2yakkCVlVzx/KUowcYplUXYpwT0hKSPE9LY=', max_length=128),
        ),
    ]
