# Generated by Django 4.2.13 on 2024-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_web_stats', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customization_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YrQxQ2QrkNNdnpn5kBGu7L$upK30kgO/NoZaODWBDKCb3+Vn0uU9L20iKZihau7hTg=', max_length=128),
        ),
    ]
