# Generated by Django 4.2.13 on 2024-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_web_stats', '0007_alter_profile_customization_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9fOQopJ61wGjuv7VKsc5Zs$WHls5kF8N+luMQJuylDj2cth1jM9Rq9atyblokiT9lA=', max_length=128),
        ),
    ]
