# Generated by Django 4.2.13 on 2024-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_web_stats', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$cysF0XjIZbggnXO7zfIjy6$/cCHyBmlI/YYJ+QRYtKhrGcrPFLIlqPCuy3nIs1o268=', max_length=128),
        ),
    ]
