# Generated by Django 4.2.13 on 2024-07-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_web_stats', '0011_rename_github_email_githubintegration_github_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$QBcOzD6aqctsg43TVE7fng$tkI6iyyA3qHQEedyfeqPxwd/yXuhY86llQlZ+ckL/Pk=', max_length=128),
        ),
    ]
